### ISSUE TITLE
Ore generation

### ISSUE THREAD

**Issue by viktordimov** [Minigeee/life-crystals#4]
Not sure if this is an issue with Life Crystals but when playing with another mod called Infinity Cave, the life crystal ores only generate in those caves below Y -64. 

Minecraft 1.20.4
Fabric
Life Crystals 1.0.2

**Comment by Minigeee** [comment]
It looks like Infinity Cave changes the world height to -128, and life crystal (and most diamonds veins) generate based on an offset from the bottom of the world. So because the bottom of the world is lower, life crystals also generate lower.

Do diamonds still generate at the same level as in vanilla?

**Comment by viktordimov** [comment]
Diamonds generate in lower quantities but still findable above -64. 
If this can't be changed I'll take it as "feature, not a bug" and adapt the mod pack around it
